name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Debugging - Print Vercel environment variables
      - name: Print Vercel environment variables
        run: |
          echo "VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}"
          echo "VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}"

      # Step 3: Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: W39rqcDHvkeTxMkdi6QjFSXx  # Vercel token
          vercel-org-id: rohit-gupta-369  # Vercel Organization ID
          vercel-project-id: prj_qNhejIOyxvQAD0igbM1JmXHU5woO  # Vercel Project ID
          github-comment: true
          github-deployment: false
